'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.ComponentModel
Imports System.Data.EntityClient
Imports System.Data.Objects
Imports System.Data.Objects.DataClasses
Imports System.Linq
Imports System.Runtime.Serialization
Imports System.Xml.Serialization

<Assembly: EdmSchemaAttribute()>
Namespace WPFPivotGridCustomServerModeSort
    #Region "Contexts"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    Partial Public Class NWindEntities
        Inherits ObjectContext

        #Region "Constructors"

        ''' <summary>
        ''' Initializes a new NWindEntities object using the connection string found in the 'NWindEntities' section of the application configuration file.
        ''' </summary>
        Public Sub New()
            MyBase.New("name=NWindEntities", "NWindEntities")
            Me.ContextOptions.LazyLoadingEnabled = True
            OnContextCreated()
        End Sub

        ''' <summary>
        ''' Initialize a new NWindEntities object.
        ''' </summary>
        Public Sub New(ByVal connectionString As String)
            MyBase.New(connectionString, "NWindEntities")
            Me.ContextOptions.LazyLoadingEnabled = True
            OnContextCreated()
        End Sub

        ''' <summary>
        ''' Initialize a new NWindEntities object.
        ''' </summary>
        Public Sub New(ByVal connection As EntityConnection)
            MyBase.New(connection, "NWindEntities")
            Me.ContextOptions.LazyLoadingEnabled = True
            OnContextCreated()
        End Sub

        #End Region

        #Region "Partial Methods"

        Partial Private Sub OnContextCreated()
        End Sub

        #End Region

        #Region "ObjectSet Properties"

        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        Public ReadOnly Property SalesPersons() As ObjectSet(Of SalesPerson)
            Get
                If (_SalesPersons Is Nothing) Then
                    _SalesPersons = MyBase.CreateObjectSet(Of SalesPerson)("SalesPersons")
                End If
                Return _SalesPersons
            End Get
        End Property
        Private _SalesPersons As ObjectSet(Of SalesPerson)

        #End Region

        #Region "AddTo Methods"

        ''' <summary>
        ''' Deprecated Method for adding a new object to the SalesPersons EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        ''' </summary>

        Public Sub AddToSalesPersons(ByVal salesPerson_Renamed As SalesPerson)
            MyBase.AddObject("SalesPersons", salesPerson_Renamed)
        End Sub

        #End Region

    End Class

    #End Region

    #Region "Entities"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmEntityTypeAttribute(NamespaceName:="NWindModel", Name:="SalesPerson"), Serializable(), DataContractAttribute(IsReference:=True)> _
    Partial Public Class SalesPerson
        Inherits EntityObject

        #Region "Factory Method"

        ''' <summary>
        ''' Create a new SalesPerson object.
        ''' </summary>
        ''' <param name="orderID">Initial value of the OrderID property.</param>
        ''' <param name="firstName">Initial value of the FirstName property.</param>
        ''' <param name="lastName">Initial value of the LastName property.</param>
        ''' <param name="productName">Initial value of the ProductName property.</param>
        ''' <param name="categoryName">Initial value of the CategoryName property.</param>
        ''' <param name="unitPrice">Initial value of the UnitPrice property.</param>
        ''' <param name="quantity">Initial value of the Quantity property.</param>
        ''' <param name="discount">Initial value of the Discount property.</param>
        ''' <param name="sales_Person">Initial value of the Sales_Person property.</param>
        Public Shared Function CreateSalesPerson(ByVal orderID As Global.System.Int32, ByVal firstName As Global.System.String, ByVal lastName As Global.System.String, ByVal productName As Global.System.String, ByVal categoryName As Global.System.String, ByVal unitPrice As Global.System.Decimal, ByVal quantity As Global.System.Int16, ByVal discount As Global.System.Single, ByVal sales_Person As Global.System.String) As SalesPerson

            Dim salesPerson_Renamed As New SalesPerson()
            salesPerson_Renamed.OrderID = orderID
            salesPerson_Renamed.FirstName = firstName
            salesPerson_Renamed.LastName = lastName
            salesPerson_Renamed.ProductName = productName
            salesPerson_Renamed.CategoryName = categoryName
            salesPerson_Renamed.UnitPrice = unitPrice
            salesPerson_Renamed.Quantity = quantity
            salesPerson_Renamed.Discount = discount
            salesPerson_Renamed.Sales_Person = sales_Person
            Return salesPerson_Renamed
        End Function

        #End Region

        #Region "Primitive Properties"

        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=True, IsNullable:=False), DataMemberAttribute()> _
        Public Property OrderID() As Global.System.Int32
            Get
                Return _OrderID
            End Get
            Set(ByVal value As System.Int32)
                If _OrderID <> value Then
                    OnOrderIDChanging(value)
                    ReportPropertyChanging("OrderID")
                    _OrderID = StructuralObject.SetValidValue(value)
                    ReportPropertyChanged("OrderID")
                    OnOrderIDChanged()
                End If
            End Set
        End Property
        Private _OrderID As Global.System.Int32
        Partial Private Sub OnOrderIDChanging(ByVal value As Global.System.Int32)
        End Sub
        Partial Private Sub OnOrderIDChanged()
        End Sub

        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=False, IsNullable:=True), DataMemberAttribute()> _
        Public Property Country() As Global.System.String
            Get
                Return _Country
            End Get
            Set(ByVal value As System.String)
                OnCountryChanging(value)
                ReportPropertyChanging("Country")
                _Country = StructuralObject.SetValidValue(value, True)
                ReportPropertyChanged("Country")
                OnCountryChanged()
            End Set
        End Property
        Private _Country As Global.System.String
        Partial Private Sub OnCountryChanging(ByVal value As Global.System.String)
        End Sub
        Partial Private Sub OnCountryChanged()
        End Sub

        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=True, IsNullable:=False), DataMemberAttribute()> _
        Public Property FirstName() As Global.System.String
            Get
                Return _FirstName
            End Get
            Set(ByVal value As System.String)
                If _FirstName <> value Then
                    OnFirstNameChanging(value)
                    ReportPropertyChanging("FirstName")
                    _FirstName = StructuralObject.SetValidValue(value, False)
                    ReportPropertyChanged("FirstName")
                    OnFirstNameChanged()
                End If
            End Set
        End Property
        Private _FirstName As Global.System.String
        Partial Private Sub OnFirstNameChanging(ByVal value As Global.System.String)
        End Sub
        Partial Private Sub OnFirstNameChanged()
        End Sub

        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=True, IsNullable:=False), DataMemberAttribute()> _
        Public Property LastName() As Global.System.String
            Get
                Return _LastName
            End Get
            Set(ByVal value As System.String)
                If _LastName <> value Then
                    OnLastNameChanging(value)
                    ReportPropertyChanging("LastName")
                    _LastName = StructuralObject.SetValidValue(value, False)
                    ReportPropertyChanged("LastName")
                    OnLastNameChanged()
                End If
            End Set
        End Property
        Private _LastName As Global.System.String
        Partial Private Sub OnLastNameChanging(ByVal value As Global.System.String)
        End Sub
        Partial Private Sub OnLastNameChanged()
        End Sub

        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=True, IsNullable:=False), DataMemberAttribute()> _
        Public Property ProductName() As Global.System.String
            Get
                Return _ProductName
            End Get
            Set(ByVal value As System.String)
                If _ProductName <> value Then
                    OnProductNameChanging(value)
                    ReportPropertyChanging("ProductName")
                    _ProductName = StructuralObject.SetValidValue(value, False)
                    ReportPropertyChanged("ProductName")
                    OnProductNameChanged()
                End If
            End Set
        End Property
        Private _ProductName As Global.System.String
        Partial Private Sub OnProductNameChanging(ByVal value As Global.System.String)
        End Sub
        Partial Private Sub OnProductNameChanged()
        End Sub

        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=True, IsNullable:=False), DataMemberAttribute()> _
        Public Property CategoryName() As Global.System.String
            Get
                Return _CategoryName
            End Get
            Set(ByVal value As System.String)
                If _CategoryName <> value Then
                    OnCategoryNameChanging(value)
                    ReportPropertyChanging("CategoryName")
                    _CategoryName = StructuralObject.SetValidValue(value, False)
                    ReportPropertyChanged("CategoryName")
                    OnCategoryNameChanged()
                End If
            End Set
        End Property
        Private _CategoryName As Global.System.String
        Partial Private Sub OnCategoryNameChanging(ByVal value As Global.System.String)
        End Sub
        Partial Private Sub OnCategoryNameChanged()
        End Sub

        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=False, IsNullable:=True), DataMemberAttribute()> _
        Public Property OrderDate() As Global.System.DateTime?
            Get
                Return _OrderDate
            End Get
            Set(ByVal value? As Date)
                OnOrderDateChanging(value)
                ReportPropertyChanging("OrderDate")
                _OrderDate = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("OrderDate")
                OnOrderDateChanged()
            End Set
        End Property
        Private _OrderDate? As Global.System.DateTime
        Partial Private Sub OnOrderDateChanging(ByVal value? As Global.System.DateTime)
        End Sub
        Partial Private Sub OnOrderDateChanged()
        End Sub

        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=True, IsNullable:=False), DataMemberAttribute()> _
        Public Property UnitPrice() As Global.System.Decimal
            Get
                Return _UnitPrice
            End Get
            Set(ByVal value As System.Decimal)
                If _UnitPrice <> value Then
                    OnUnitPriceChanging(value)
                    ReportPropertyChanging("UnitPrice")
                    _UnitPrice = StructuralObject.SetValidValue(value)
                    ReportPropertyChanged("UnitPrice")
                    OnUnitPriceChanged()
                End If
            End Set
        End Property
        Private _UnitPrice As Global.System.Decimal
        Partial Private Sub OnUnitPriceChanging(ByVal value As Global.System.Decimal)
        End Sub
        Partial Private Sub OnUnitPriceChanged()
        End Sub

        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=True, IsNullable:=False), DataMemberAttribute()> _
        Public Property Quantity() As Global.System.Int16
            Get
                Return _Quantity
            End Get
            Set(ByVal value As System.Int16)
                If _Quantity <> value Then
                    OnQuantityChanging(value)
                    ReportPropertyChanging("Quantity")
                    _Quantity = StructuralObject.SetValidValue(value)
                    ReportPropertyChanged("Quantity")
                    OnQuantityChanged()
                End If
            End Set
        End Property
        Private _Quantity As Global.System.Int16
        Partial Private Sub OnQuantityChanging(ByVal value As Global.System.Int16)
        End Sub
        Partial Private Sub OnQuantityChanged()
        End Sub

        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=True, IsNullable:=False), DataMemberAttribute()> _
        Public Property Discount() As Global.System.Single
            Get
                Return _Discount
            End Get
            Set(ByVal value As System.Single)
                If _Discount <> value Then
                    OnDiscountChanging(value)
                    ReportPropertyChanging("Discount")
                    _Discount = StructuralObject.SetValidValue(value)
                    ReportPropertyChanged("Discount")
                    OnDiscountChanged()
                End If
            End Set
        End Property
        Private _Discount As Global.System.Single
        Partial Private Sub OnDiscountChanging(ByVal value As Global.System.Single)
        End Sub
        Partial Private Sub OnDiscountChanged()
        End Sub

        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=False, IsNullable:=True), DataMemberAttribute()> _
        Public Property Extended_Price() As Global.System.Decimal?
            Get
                Return _Extended_Price
            End Get
            Set(ByVal value? As System.Decimal)
                OnExtended_PriceChanging(value)
                ReportPropertyChanging("Extended_Price")
                _Extended_Price = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("Extended_Price")
                OnExtended_PriceChanged()
            End Set
        End Property
        Private _Extended_Price? As Global.System.Decimal
        Partial Private Sub OnExtended_PriceChanging(ByVal value? As Global.System.Decimal)
        End Sub
        Partial Private Sub OnExtended_PriceChanged()
        End Sub

        ''' <summary>
        ''' No Metadata Documentation available.
        ''' </summary>
        <EdmScalarPropertyAttribute(EntityKeyProperty:=True, IsNullable:=False), DataMemberAttribute()> _
        Public Property Sales_Person() As Global.System.String
            Get
                Return _Sales_Person
            End Get
            Set(ByVal value As System.String)
                If _Sales_Person <> value Then
                    OnSales_PersonChanging(value)
                    ReportPropertyChanging("Sales_Person")
                    _Sales_Person = StructuralObject.SetValidValue(value, False)
                    ReportPropertyChanged("Sales_Person")
                    OnSales_PersonChanged()
                End If
            End Set
        End Property
        Private _Sales_Person As Global.System.String
        Partial Private Sub OnSales_PersonChanging(ByVal value As Global.System.String)
        End Sub
        Partial Private Sub OnSales_PersonChanged()
        End Sub

        #End Region


    End Class

    #End Region


End Namespace
